apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: db-karlo
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql-password
        ports:
        - containerPort: 3306
          name: mysql