apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api-karlo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: servicios-cloud-karlo:1
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_PASSWORD
              value: mysql-password
      imagePullSecrets:
        - name: your-image-pull-secret
